export const siteConfig = {
  businessName: "Image Contracting",
  tagline: "Built right. Finished clean.",
  trade: "General Contracting / Home Remodeling",
  phone: "603-716-1522",
  phoneHref: "tel:6037161522",
  email: "info@imagecontracting.com",
  projectsEmail: "projects@imagecontracting.com",
  address: {
    street: "Bedford",
    city: "Bedford",
    state: "NH",
    zip: "03110",
    full: "Bedford, NH 03110",
  },
  serviceArea: "Bedford, Manchester, Amherst, Nashua, and surrounding areas in Southern NH",
  serviceAreaExtended: "Bedford, Manchester, Nashua, Concord, and the Seacoast region of New Hampshire",
  license: "NH License #123456",
  insurance: "Fully Insured & Bonded ($2M)",
  bbb: "A+ BBB Accredited",
  hours: {
    weekday: "Mon - Fri: 8:00 AM - 6:00 PM",
    saturday: "Sat: 9:00 AM - 1:00 PM",
  },
  stats: {
    years: "15+",
    projects: "500+",
    satisfaction: "100%",
    rating: "5-Star",
  },
  founded: "2009",
  primaryDomain: process.env.NEXT_PUBLIC_PRIMARY_DOMAIN || "imagecontracting.com",
  googleReviewLink: process.env.NEXT_PUBLIC_GOOGLE_REVIEW_LINK || "#",
  gtmId: process.env.NEXT_PUBLIC_GTM_ID || "",
  nav: [
    { label: "Services", href: "/services" },
    { label: "Projects", href: "/projects" },
    { label: "About", href: "/about" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
  footerServices: [
    { label: "Residential", href: "/services" },
    { label: "Commercial", href: "/services" },
    { label: "Remodeling", href: "/services" },
    { label: "Kitchens", href: "/services/kitchen-remodeling" },
    { label: "Bathrooms", href: "/services" },
  ],
  footerCompany: [
    { label: "About Us", href: "/about" },
    { label: "Reviews", href: "/reviews" },
    { label: "Portfolio", href: "/projects" },
    { label: "Contact Us", href: "/contact" },
    { label: "Privacy Policy", href: "/privacy" },
  ],
} as const;
